CREATE TABLE USUARIO(
ID INT NOT NULL AUTO_INCREMENT,
NOME_COMPLETO VARCHAR(100) NOT NULL,
EMAIL VARCHAR(100) NOT NULL,
SENHA VARCHAR(100) NOT NULL,
GENERO VARCHAR(45) NOT NULL,
CPF INT NOT NULL,
DATA_NASCIMENTO VARCHAR(45) NOT NULL,
CELULAR INT NOT NULL,
CONSTRAINT USU_PK PRIMARY KEY (ID));

CREATE TABLE EMPRESA(
ID INT NOT NULL AUTO_INCREMENT,
TIPO INT NOT NULL,
CNPJ VARCHAR(45) NOT NULL,
EMAIL VARCHAR(100) NOT NULL,
NOME VARCHAR(45) NOT NULL,
NOME_FANTASMA VARCHAR(45) NOT NULL,
SENHA VARCHAR(60),
CONSTRAINT EMP_PK PRIMARY KEY (ID));

CREATE TABLE DENUNCIA(
ID INT NOT NULL AUTO_INCREMENT,
COMENTARIO VARCHAR(300) NOT NULL,
DATA_RECLAMACAO DATE NOT NULL,
TITULO VARCHAR(45) NOT NULL,
HORA TIME NOT NULL,
LONGITUDE VARCHAR(100) NOT NULL,
LATITUDE VARCHAR(100) NOT NULL,
USU_ID INT NOT NULL,
EMP_ID INT NOT NULL,
CONSTRAINT DEN_PK PRIMARY KEY (ID),
CONSTRAINT DEN_USU_FK FOREIGN KEY (USU_ID) REFERENCES USUARIO (ID),
CONSTRAINT DEN_EMP_FK FOREIGN KEY (EMP_ID) REFERENCES EMPRESA (ID));

CREATE TABLE REACAO(
USU_ID INT NOT NULL,
DEN_ID INT NOT NULL,
LIKE_DESLIKE INT NULL,
CONSTRAINT REA_USU_FK FOREIGN KEY (USU_ID) REFERENCES USUARIO (ID),
CONSTRAINT REA_DEN_FK FOREIGN KEY (DEN_ID) REFERENCES DENUNCIA (ID));

CREATE TABLE COMENTARIO(
ID INT NOT NULL AUTO_INCREMENT,
COMENTARIO_ENGAJAR VARCHAR(2500) NULL,
USU_ID INT NOT NULL,
DEN_ID INT NOT NULL, 
CONSTRAINT COM_PK PRIMARY KEY (ID),
CONSTRAINT COM_USU_FK FOREIGN KEY (USU_ID) REFERENCES USUARIO (ID),
CONSTRAINT COM_DEN_FK FOREIGN KEY (DEN_ID) REFERENCES DENUNCIA (ID));